[theme]
# Primary accent color for interactive elements.
primaryColor = "#d33682"

# Background color for the main content area.
backgroundColor = "#EBECF0"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#8691A2"

# Color used for almost all text.
textColor = "black"


[client]
toolbarMode = "minimal" 